name: Update Coverage in README
on:
    push:
        paths-ignore:
            - '**/*.md'
            - '**/*.yml'
            - '.github/**'
            - 'data/**'
            - 'dist/**'

jobs:
    update-coverage-in-readme:
        name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.2.0
        runs-on: ubuntu-latest
        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: NPM Cache
              id: npm-cache
              uses: actions/cache@v3
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-npm

            - name: Install Dependencies
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run Tests
              run: npm run test:coverage | tee ./coverage.txt

            - name: 'Report Coverage'
                # Set if: always() to also generate the report if tests are failing
                # Only works if you set `reportOnFailure: true` in your vite config as specified above
              if: always()
              uses:  davelosert/vitest-coverage-report-action@v2

#            - name: Jest Coverage Comment (legacy, this needs to be updated to use vitest)
#              id: coverageComment
#              uses: MishaKav/jest-coverage-comment@main
#              with:
#                hide-comment: true
#                coverage-path: ./coverage.txt
#                junitxml-path: ./coverage/junit.xml

# old action to update badge does not work anymore - need to figure out how to adapt it to current workflow
#            - name: Create the badge
#              #              if: github.ref == 'refs/heads/main'
#              uses: schneegans/dynamic-badges-action@v1.6.0
#              with:
#                auth: ${{ secrets.GIST_SECRET }}
#                gistID: 7571a4c577e80cce945baedaba153669
#                filename: test.json
#                label: coverage
#                message: ${{ steps.coverageComment.outputs.coverage }}%
#                color: ${{ steps.coverageComment.outputs.color }}
#                namedLogo: javascript
